### ISSUE TITLE
Create AgTern API service

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#83]
### Context

Our frontend needs a service that can communicate with the backend. This service separates all the frontend logic from the backend communication. Frontend components that need to access any data from the backend will "inject" this service as a dependency. Read about Angular services [here](https://angular.io/guide/architecture-services).

### TODO

- [x] Create an `AgTernAPI` service using the `ng generate service [name] [options]` command
- [x] Implement functions in AgTernAPI that communicate with the backend API; for example, since we will need to get all internships to populate on the frontend, we can create a `getAllInternships` function in the service that makes an HTTP GET request to the `/internships` route. This allows any frontend component to inject the `AgTernAPI` service and call the `getAllInternships` function therein to access all the data

### Notes

**Comment by JeremyEastham** [comment]
The fastest and easiest way to do this would be to generate it using `openapi-typescript-codegen`. At first it can be done by running a couple of commands. Eventually we will want to automate this (ex: run the commands every time we run the server so that the client is always updated).

**FastAPI Documentation:** https://fastapi.tiangolo.com/advanced/generate-clients/

**Comment by johndpjr** [comment]
I see- this is what you were talking about with regards to the integration between the two software stacks. I'll look into this
